namespace ZCrew.Extensions.CodeAnalysis.CSharp.IsType;

/// <summary>
///     The hand-authored source for the <c>IsTypeAttribute</c> definitions emitted into consuming projects. This is
///     emitted directly (rather than via the <c>[Microsoft.CodeAnalysis.Embedded]</c> pipeline) so the feature is
///     self-contained.
/// </summary>
internal static class IsTypeAttributeSource
{
    /// <summary>
    ///     The hint name used when emitting the attribute definitions.
    /// </summary>
    public const string HintName = "IsTypeAttribute.g.cs";

    /// <summary>
    ///     The source for the generic and non-generic <c>IsTypeAttribute</c> definitions.
    /// </summary>
    public const string Source = """
        // <auto-generated/>
        #nullable enable
        #pragma warning disable 0618, 1591, 8019

        namespace ZCrew.Extensions.CodeAnalysis.CSharp;

        /// <summary>
        ///     Marks a partial method as a fast Roslyn type check for <typeparamref name="T"/>. The method must return a
        ///     <see cref="bool"/> and accept a single <c>Microsoft.CodeAnalysis.ISymbol</c> (or a derived symbol type).
        /// </summary>
        /// <typeparam name="T">The type to check for.</typeparam>
        [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = false, Inherited = false)]
        [global::System.CodeDom.Compiler.GeneratedCode("ZCrew.Extensions.CodeAnalysis.CSharp", "0.0.0.0")]
        internal sealed class IsTypeAttribute<T> : global::System.Attribute
        {
        }

        /// <summary>
        ///     Marks a partial method as a fast Roslyn type check for the provided type. The method must return a
        ///     <see cref="bool"/> and accept a single <c>Microsoft.CodeAnalysis.ISymbol</c> (or a derived symbol type).
        /// </summary>
        [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = false, Inherited = false)]
        [global::System.CodeDom.Compiler.GeneratedCode("ZCrew.Extensions.CodeAnalysis.CSharp", "0.0.0.0")]
        internal sealed class IsTypeAttribute : global::System.Attribute
        {
            /// <summary>
            ///     Creates a new <see cref="IsTypeAttribute"/>.
            /// </summary>
            /// <param name="type">The type to check for.</param>
            public IsTypeAttribute(global::System.Type type)
            {
                this.Type = type;
            }

            /// <summary>
            ///     The type to check for.
            /// </summary>
            public global::System.Type Type { get; }
        }

        """;
}
