// <auto-generated/>
#nullable enable
#pragma warning disable 0618, 1591, 8019

namespace AttributeTests;

/// <summary>
///     Attribute data for <see cref="TestAttribute{TService, TImplementation}"/>.
/// </summary>
[global::Microsoft.CodeAnalysis.Embedded]
[global::System.CodeDom.Compiler.GeneratedCode("ZCrew.Extensions.CodeAnalysis.CSharp", "0.0.0.0")]
internal partial record TestAttributeData_2
{
    public global::Microsoft.CodeAnalysis.ITypeSymbol Service = null!;
    public global::Microsoft.CodeAnalysis.ITypeSymbol Implementation = null!;
}
internal static partial class AttributeDataExtensions
{
    public static bool TryGetTestAttributeData_2(this global::Microsoft.CodeAnalysis.AttributeData attributeData, [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] out TestAttributeData_2? data)
    {
        foreach (var constructor in TestAttributeData_2_Constructor.TestAttributeData_2_Constructors)
        {
            if (constructor.TryCreateAttributeFor(attributeData, out data))
            {
                return true;
            }
        }
        data = default;
        return false;
    }
}
internal static partial class SyntaxValueProviderExtensions
{
    public static global::Microsoft.CodeAnalysis.IncrementalValuesProvider<T> ForTestAttributeData_2<T>(this global::Microsoft.CodeAnalysis.SyntaxValueProvider syntaxProvider, global::System.Func<global::Microsoft.CodeAnalysis.SyntaxNode, global::System.Threading.CancellationToken, bool> predicate, global::System.Func<global::Microsoft.CodeAnalysis.GeneratorAttributeSyntaxContext, global::System.Collections.Immutable.ImmutableArray<TestAttributeData_2>, global::System.Threading.CancellationToken, T> transform)
    {
        var results = syntaxProvider.ForAttributeWithMetadataName(
            "AttributeTests.TestAttribute`2",
            predicate,
            (context, cancellationToken) =>
            {
                var builder = global::System.Collections.Immutable.ImmutableArray.CreateBuilder<TestAttributeData_2>(context.Attributes.Length);
                foreach (var attribute in context.Attributes)
                {
                    cancellationToken.ThrowIfCancellationRequested();
                    if (attribute.TryGetTestAttributeData_2(out var data))
                    {
                        builder.Add(data);
                    }
                }
                if (builder.Count == 0)
                {
                    return (Value: default(T)!, IsMatch: false);
                }
                return (Value: transform(context, builder.ToImmutable(), cancellationToken), IsMatch: true);
            });
        var matches = global::Microsoft.CodeAnalysis.IncrementalValueProviderExtensions.Where(results, result => result.IsMatch);
        return global::Microsoft.CodeAnalysis.IncrementalValueProviderExtensions.Select(matches, (result, _) => result.Value);
    }
}
file sealed class TestAttributeData_2_Constructor : global::ZCrew.Extensions.CodeAnalysis.CSharp.AttributeConstructor<TestAttributeData_2>
{
    private static readonly TestAttributeData_2_Constructor constructor0 = new([TestAttributeData_2_TypeParameter.Service, TestAttributeData_2_TypeParameter.Implementation]);
    public static readonly TestAttributeData_2_Constructor[] TestAttributeData_2_Constructors = [constructor0];
    protected override string AttributeMetadataName => "AttributeTests.TestAttribute`2";
    public TestAttributeData_2_Constructor(global::ZCrew.Extensions.CodeAnalysis.CSharp.AttributeTypeParameter<TestAttributeData_2>[] typeParameters) : base(typeParameters, [], []) { }
}
file sealed class TestAttributeData_2_TypeParameter : global::ZCrew.Extensions.CodeAnalysis.CSharp.AttributeTypeParameter<TestAttributeData_2>
{
    public static readonly TestAttributeData_2_TypeParameter Service = new((model, symbol) => model.Service = symbol);
    public static readonly TestAttributeData_2_TypeParameter Implementation = new((model, symbol) => model.Implementation = symbol);
    public TestAttributeData_2_TypeParameter(global::System.Action<TestAttributeData_2, global::Microsoft.CodeAnalysis.ITypeSymbol> valueAction) : base(valueAction) { }
}
