// <auto-generated/>
#nullable enable
#pragma warning disable 0618, 1591, 8019

namespace AttributeTests;

/// <summary>
///     Attribute data for <see cref="TestAttribute"/>.
/// </summary>
[global::Microsoft.CodeAnalysis.Embedded]
[global::System.CodeDom.Compiler.GeneratedCode("ZCrew.Extensions.CodeAnalysis.CSharp", "0.0.0.0")]
internal partial record TestAttributeData
{
    public string Name = null!;
    public string? Extra;
}
internal static partial class AttributeDataExtensions
{
    public static bool TryGetTestAttributeData(this global::Microsoft.CodeAnalysis.AttributeData attributeData, [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] out TestAttributeData? data)
    {
        foreach (var constructor in TestAttributeDataConstructor.TestAttributeDataConstructors)
        {
            if (constructor.TryCreateAttributeFor(attributeData, out data))
            {
                return true;
            }
        }
        data = default;
        return false;
    }
}
internal static partial class SyntaxValueProviderExtensions
{
    public static global::Microsoft.CodeAnalysis.IncrementalValuesProvider<T> ForTestAttributeData<T>(this global::Microsoft.CodeAnalysis.SyntaxValueProvider syntaxProvider, global::System.Func<global::Microsoft.CodeAnalysis.SyntaxNode, global::System.Threading.CancellationToken, bool> predicate, global::System.Func<global::Microsoft.CodeAnalysis.GeneratorAttributeSyntaxContext, global::System.Collections.Immutable.ImmutableArray<TestAttributeData>, global::System.Threading.CancellationToken, T> transform)
    {
        var results = syntaxProvider.ForAttributeWithMetadataName(
            "AttributeTests.TestAttribute",
            predicate,
            (context, cancellationToken) =>
            {
                var builder = global::System.Collections.Immutable.ImmutableArray.CreateBuilder<TestAttributeData>(context.Attributes.Length);
                foreach (var attribute in context.Attributes)
                {
                    cancellationToken.ThrowIfCancellationRequested();
                    if (attribute.TryGetTestAttributeData(out var data))
                    {
                        builder.Add(data);
                    }
                }
                if (builder.Count == 0)
                {
                    return (Value: default(T)!, IsMatch: false);
                }
                return (Value: transform(context, builder.ToImmutable(), cancellationToken), IsMatch: true);
            });
        var matches = global::Microsoft.CodeAnalysis.IncrementalValueProviderExtensions.Where(results, result => result.IsMatch);
        return global::Microsoft.CodeAnalysis.IncrementalValueProviderExtensions.Select(matches, (result, _) => result.Value);
    }
}
file sealed class TestAttributeDataConstructor : global::ZCrew.Extensions.CodeAnalysis.CSharp.AttributeConstructor<TestAttributeData>
{
    private static readonly TestAttributeDataConstructor constructor0 = new();
    public static readonly TestAttributeDataConstructor[] TestAttributeDataConstructors = [constructor0];
    protected override string AttributeMetadataName => "AttributeTests.TestAttribute";
    public TestAttributeDataConstructor() : base([], [], TestAttributeDataNamedParameter.TestAttributeDataNamedParameters) { }
}
file sealed class TestAttributeDataNamedParameter : global::ZCrew.Extensions.CodeAnalysis.CSharp.AttributeNamedParameter<TestAttributeData>
{
    private static readonly TestAttributeDataNamedParameter Name = new("Name", (model, _, constant) => global::ZCrew.Extensions.CodeAnalysis.CSharp.TypedConstantExtensions.GetValue(constant, out model.Name));
    private static readonly TestAttributeDataNamedParameter Extra = new("Extra", (model, _, constant) => global::ZCrew.Extensions.CodeAnalysis.CSharp.TypedConstantExtensions.GetValue(constant, out model.Extra));
    internal static readonly global::ZCrew.Extensions.CodeAnalysis.CSharp.AttributeNamedParameter<TestAttributeData>[] TestAttributeDataNamedParameters = [Name, Extra];
    public TestAttributeDataNamedParameter(string name, global::System.Action<TestAttributeData, string, global::Microsoft.CodeAnalysis.TypedConstant> valueAction) : base(name, valueAction) { }
}
