// <auto-generated/>
#nullable enable
#pragma warning disable 0618, 1591, 8019

namespace AttributeTests;

[global::Microsoft.CodeAnalysis.Embedded]
[global::System.CodeDom.Compiler.GeneratedCode("ZCrew.Extensions.CodeAnalysis.CSharp", "0.0.0.0")]
internal static partial class TestAttributeSourceText
{
    public static readonly global::Microsoft.CodeAnalysis.Text.SourceText SourceText = global::Microsoft.CodeAnalysis.Text.SourceText.From(
        """
        using System;
        using System.Diagnostics.CodeAnalysis;
        
        namespace AttributeTests;
        
        // The constructor opts out of the compiler's required-member enforcement, so 'Extra' is no longer guaranteed
        [Microsoft.CodeAnalysis.Embedded]
        public class TestAttribute : Attribute
        {
            [SetsRequiredMembers]
            public TestAttribute(string name)
            {
                Extra = name;
            }
        
            public required string Extra { get; set; }
        }
        
        """,
        global::System.Text.Encoding.UTF8
    );
    
    public static void AddTestAttributeDefinition(this global::Microsoft.CodeAnalysis.IncrementalGeneratorPostInitializationContext context)
    {
        context.AddSource("AttributeTests.TestAttributeSourceText.g.cs", SourceText);
    }
}
