// <auto-generated/>
#nullable enable
#pragma warning disable 0618, 1591, 8019

namespace IsTypeTests;

partial class SymbolChecks
{
    public static partial bool IsTask([global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] global::Microsoft.CodeAnalysis.ISymbol? symbol) =>
        symbol is global::Microsoft.CodeAnalysis.INamedTypeSymbol
        {
            Name: "Task",
            Arity: 1,
            TypeArguments:
            [
                global::Microsoft.CodeAnalysis.INamedTypeSymbol
                {
                    Name: "List",
                    Arity: 1,
                    TypeArguments: [{ SpecialType: global::Microsoft.CodeAnalysis.SpecialType.System_String }],
                    ContainingType: null,
                    ContainingNamespace:
                    {
                        Name: "Generic",
                        ContainingNamespace:
                        {
                            Name: "Collections",
                            ContainingNamespace: { Name: "System", ContainingNamespace.IsGlobalNamespace: true }
                        }
                    }
                }
            ],
            ContainingType: null,
            ContainingNamespace:
            {
                Name: "Tasks",
                ContainingNamespace:
                {
                    Name: "Threading",
                    ContainingNamespace: { Name: "System", ContainingNamespace.IsGlobalNamespace: true }
                }
            }
        };
}
