// <auto-generated/>
#nullable enable
#pragma warning disable 0618, 1591, 8019

namespace IsTypeTests;

partial class SymbolChecks
{
    public static partial bool IsDisposable([global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] global::Microsoft.CodeAnalysis.ITypeSymbol? symbol) =>
        symbol is global::Microsoft.CodeAnalysis.ITypeSymbol
        {
            SpecialType: global::Microsoft.CodeAnalysis.SpecialType.System_IDisposable
        };
}
