using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using ZCrew.Extensions.CodeAnalysis.CSharp.EmbeddedAttribute.Models;
using ZCrew.Extensions.CodeAnalysis.CSharp.Text;

namespace ZCrew.Extensions.CodeAnalysis.CSharp.EmbeddedAttribute.SourceGenerators;

internal static class ParameterSourceGenerator
{
    private const string GeneratorAssemblyName = "ZCrew.Extensions.CodeAnalysis.CSharp";

    public static void Generate(SourceProductionContext context, EmbeddedAttributeGroup group)
    {
        var hintName = string.IsNullOrEmpty(group.Namespace)
            ? $"{group.BaseName}Parameter.g.cs"
            : $"{group.Namespace}.{group.BaseName}Parameter.g.cs";

        var source = GenerateSource(group);
        context.AddSource(hintName, SourceText.From(source, Encoding.UTF8));
    }

    private static string GenerateSource(EmbeddedAttributeGroup group)
    {
        var baseName = group.BaseName;
        var builderType = $"I{baseName}DataBuilder";
        var builder = new FormattedStringBuilder();

        builder
            .AppendAutoGeneratedComment()
            .AppendNullableEnable()
            .AppendCommonPragmaDisable()
            .AppendLine()
            .AppendFileScopedNamespaceDeclaration(group.Namespace)
            .AppendLine()
            .AppendEmbeddedAttribute()
            .AppendGeneratedAttribute(GeneratorAssemblyName)
            .Append($"internal class {baseName}Parameter")
            .AppendLine()
            .Append($"    : global::ZCrew.Extensions.CodeAnalysis.CSharp.AttributeParameter<{builderType}>")
            .AppendLine()
            .Append('{')
            .Indent();

        // Generate static readonly fields for each unique parameter
        foreach (var param in group.UniqueParameters)
        {
            var pascalName = NamingHelper.ToPascalCase(param.Name);
            builder
                .AppendLine()
                .Append($"public static readonly {baseName}Parameter {pascalName} = new(")
                .Indent()
                .AppendLine()
                .Append($"\"{param.FullyQualifiedType}\",")
                .AppendLine()
                .Append($"(builder, constant) => builder.With{pascalName}(constant)")
                .Unindent()
                .AppendLine()
                .Append(");");
        }

        // Generate constructor
        builder
            .AppendLine()
            .AppendLine()
            .Append($"public {baseName}Parameter(")
            .Indent()
            .AppendLine()
            .Append("string type,")
            .AppendLine()
            .Append($"global::System.Action<{builderType}, global::Microsoft.CodeAnalysis.TypedConstant> valueAction")
            .Unindent()
            .AppendLine()
            .Append(") : base(type, valueAction) { }");

        builder.Unindent().AppendLine().Append('}').AppendLine();

        return builder.ToString();
    }
}
