using Microsoft.CodeAnalysis;
using ZCrew.Extensions.CodeAnalysis.CSharp.Embedded.Models;
using ZCrew.Extensions.CodeAnalysis.CSharp.Text;

namespace ZCrew.Extensions.CodeAnalysis.CSharp.Embedded.Emitters;

internal static class EmbeddedAbstractionSourceTextEmitter
{
    private const string GeneratorAssemblyName = "ZCrew.Extensions.CodeAnalysis.CSharp";

    public static void Emit(SourceProductionContext context, EmbeddedAttributeSourceText sourceText)
    {
        context.CancellationToken.ThrowIfCancellationRequested();

        var names = new EmbeddedAbstractionNames(sourceText.Name, sourceText.Namespace, sourceText.Arity);
        var builder = new FormattedStringBuilder();

        builder
            .AppendAutoGeneratedComment()
            .AppendNullableEnable()
            .AppendCommonPragmaDisable()
            .AppendLine()
            .AppendFileScopedNamespaceDeclaration(sourceText.Namespace)
            .AppendLine()
            .AppendEmbeddedAttribute()
            .AppendGeneratedAttribute(GeneratorAssemblyName)
            .Append($"internal static partial class {names.SourceTextClass}")
            .AppendLine()
            .AppendBlock(classBlock =>
            {
                classBlock
                    .Append(
                        "public static readonly global::Microsoft.CodeAnalysis.Text.SourceText SourceText = global::Microsoft.CodeAnalysis.Text.SourceText.From("
                    )
                    .Indent()
                    .AppendLine()
                    .AppendRawString(sourceText.SourceText)
                    .Append(',')
                    .AppendLine()
                    .Append("global::System.Text.Encoding.UTF8")
                    .Unindent()
                    .AppendLine()
                    .AppendLine(");")
                    .AppendLine()
                    .Append("public static void ")
                    .Append(names.DefinitionMethod)
                    .Append(
                        "(this global::Microsoft.CodeAnalysis.IncrementalGeneratorPostInitializationContext context)"
                    )
                    .AppendLine()
                    .AppendBlock(methodBlock =>
                    {
                        methodBlock.Append($"context.AddSource(\"{names.SourceTextHintName}\", SourceText);");
                    });
            })
            .AppendLine();

        context.AddSource(names.SourceTextHintName, builder.ToSourceText());
    }
}
