using Microsoft.CodeAnalysis;
using ZCrew.Extensions.CodeAnalysis.CSharp.Embedded.Models;
using ZCrew.Extensions.CodeAnalysis.CSharp.Text;

namespace ZCrew.Extensions.CodeAnalysis.CSharp.Embedded.Emitters;

internal static class EmbeddedAttributeInfoEmitter
{
    public static void Emit(SourceProductionContext context, EmbeddedAttributeInfo info)
    {
        context.CancellationToken.ThrowIfCancellationRequested();

        var names = new EmbeddedAttributeNames(info.Name, info.Namespace, info.Arity);
        var builder = new FormattedStringBuilder();

        builder
            .AppendAutoGeneratedComment()
            .AppendNullableEnable()
            .AppendCommonPragmaDisable()
            .AppendLine()
            .AppendFileScopedNamespaceDeclaration(info.Namespace)
            .AppendLine();
        AttributeDataEmitter.Emit(builder, info, names);
        AttributeDataExtensionEmitter.Emit(builder, names);
        SyntaxValueProviderExtensionEmitter.Emit(builder, names);
        ConstructorEmitter.Emit(builder, info, names);
        ParameterEmitter.Emit(builder, info, names);
        TypeParameterEmitter.Emit(builder, info, names);
        NamedParameterEmitter.Emit(builder, info, names);

        context.AddSource(names.AttributeDataHintName, builder.ToSourceText());
    }
}
