<Project>
  <!-- This makes sure the outer Directory.Build.props file in the root of the solution is read and applied -->
  <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))"/>

  <!-- Common properties for all test projects -->
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
  </PropertyGroup>

  <PropertyGroup>
    <TargetFrameworks>net9.0;net10.0</TargetFrameworks>
    <RoslynVersion Condition="'$(TargetFramework)' == 'net9.0'">4.14.0</RoslynVersion>
    <RoslynVersion Condition="'$(TargetFramework)' != 'net9.0'">5.9.0</RoslynVersion>
  </PropertyGroup>

  <!-- Common packages for all test projects -->
  <ItemGroup>
    <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" />
    <PackageReference Include="xunit.v3" />
  </ItemGroup>

  <!-- Exclude test projects from code coverage -->
  <ItemGroup>
    <AssemblyAttribute Include="System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage" />
  </ItemGroup>

  <!-- Global usings for all test projects -->
  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>
</Project>
