namespace ZCrew.Extensions.CodeAnalysis.CSharp.Text;

/// <summary>
///     Extensions for <see cref="FormattedStringBuilder"/>.
/// </summary>
public static class FormattedStringBuilderExtensions
{
    extension(FormattedStringBuilder builder)
    {
        /// <summary>
        ///     Appends the auto-generated comment that some tools will look for.
        /// </summary>
        /// <returns>A reference to this instance after the append operation has completed.</returns>
        public FormattedStringBuilder AppendAutoGeneratedComment()
        {
            return builder.AppendLine("// <auto-generated/>");
        }

        /// <summary>
        ///     Appends a directive to enable nullability.
        /// </summary>
        /// <returns>A reference to this instance after the append operation has completed.</returns>
        public FormattedStringBuilder AppendNullableEnable()
        {
            return builder.AppendLine("#nullable enable");
        }

        /// <summary>
        ///     Appends the common <c>pragma warning disable</c> options for source generators.
        ///     <list type="numbered">
        ///         <listheader>
        ///             <term>Warning</term>
        ///             <description>Reason</description>
        ///         </listheader>
        ///         <item>
        ///             <term><c>CS0618</c></term>
        ///             <description>The user may use <see cref="ObsoleteAttribute"/> on their own types.</description>
        ///         </item>
        ///         <item>
        ///             <term><c>CS1591</c></term>
        ///             <description>The generated code will not typically provide documentation.</description>
        ///         </item>
        ///         <item>
        ///             <term><c>CS8019</c></term>
        ///             <description>
        ///                 Extension methods aren't as readable when referenced statically. Instead, providing a using
        ///                 directive will be clearer to the user. At times, the using directive may not be necessary
        ///                 but this can be ignored.
        ///             </description>
        ///         </item>
        ///     </list>
        /// </summary>
        /// <returns>A reference to this instance after the append operation has completed.</returns>
        public FormattedStringBuilder AppendCommonPragmaDisable()
        {
            return builder.AppendLine("#pragma warning disable 0618, 1591, 8019");
        }

        /// <summary>
        ///     Appends a <see cref="System.CodeDom.Compiler.GeneratedCodeAttribute"/> with information about the source
        ///     generator that created this source.
        /// </summary>
        /// <param name="assemblyName">
        ///     The assembly name for the <see cref="System.CodeDom.Compiler.GeneratedCodeAttribute.Tool"/> value.
        /// </param>
        /// <param name="assemblyVersion">
        ///     The assembly version for the <see cref="System.CodeDom.Compiler.GeneratedCodeAttribute.Version"/> value.
        /// </param>
        /// <returns>A reference to this instance after the append operation has completed.</returns>
        public FormattedStringBuilder AppendGeneratedAttribute(string assemblyName, string assemblyVersion = "0.0.0.0")
        {
            return builder.AppendLine(
                $"[global::System.CodeDom.Compiler.GeneratedCode(\"{assemblyName}\", \"{assemblyVersion}\")]"
            );
        }

        /// <summary>
        ///     Appends a <c>EmbeddedAttribute</c> to a class.
        /// </summary>
        /// <returns>A reference to this instance after the append operation has completed.</returns>
        public FormattedStringBuilder AppendEmbeddedAttribute()
        {
            return builder.AppendLine("[global::Microsoft.CodeAnalysis.Embedded]");
        }

        /// <summary>
        ///     Appends a <see langword="typeof"/> expression with opening and closing round brackets.
        /// </summary>
        /// <param name="typeName">The name of the type.</param>
        /// <returns>A reference to this instance after the append operation has completed.</returns>
        /// <example>Given <c>"string"</c> this would append <c>"typeof(string)"</c>.</example>
        public FormattedStringBuilder AppendTypeof(string typeName)
        {
            return builder.Append("typeof(").Append(typeName).Append(')');
        }

        /// <summary>
        ///     Appends a <see langword="namespace"/> declaration if the <paramref name="namespace"/> is neither
        ///     <see langword="null"/> nor whitespace.
        /// </summary>
        /// <param name="namespace">The namespace to declare, if present.</param>
        /// <returns>A reference to this instance after the append operation has completed.</returns>
        public FormattedStringBuilder AppendFileScopedNamespaceDeclaration(string? @namespace)
        {
            if (string.IsNullOrWhiteSpace(@namespace))
            {
                return builder;
            }

            return builder.Append("namespace ").Append(@namespace!).AppendLine(';');
        }

        /// <summary>
        ///     Appends a raw <see cref="string"/> (denoted by <c>"""</c>).
        /// </summary>
        /// <param name="rawString">The raw string to write.</param>
        /// <returns>A reference to this instance after the append operation has completed.</returns>
        /// <example>
        /// <code>
        ///     """
        ///     {
        ///         "value": "Foo"
        ///     }
        ///     """
        /// </code>
        /// </example>
        public FormattedStringBuilder AppendRawString(string rawString)
        {
            builder.AppendLine("\"\"\"");

            // Strip the newline characters to provide consistent newline characters
            foreach (var line in rawString.Split(["\r\n", "\n"], StringSplitOptions.None))
            {
                builder.AppendLine(line);
            }

            builder.Append("\"\"\"");
            return builder;
        }

        /// <summary>
        ///     Appends a multiline <see cref="string"/>.
        /// </summary>
        /// <param name="lines">The multiline string to write.</param>
        /// <returns>A reference to this instance after the append operation has completed.</returns>
        /// <example>
        /// <code>
        ///     private const string Comment =
        ///         """
        ///         /// &lt;summary&gt;
        ///         /// Generated method for registering a component.
        ///         /// &lt;/summary&gt;
        ///         """;
        ///     private string comment = new FormattedStringBuilder()
        ///         .Append('{')
        ///         .Indent()
        ///         .AppendLine()
        ///         .AppendMultiline(Comment)
        ///         .Append("public void Register() {}")
        ///         .Unindent()
        ///         .AppendLine()
        ///         .Append('}')
        ///         .ToString();
        /// </code>
        /// Would generate:
        /// <code>
        ///     {
        ///         /// &lt;summary&gt;
        ///         /// Generated method for registering a component.
        ///         /// &lt;/summary&gt;
        ///         public void Register() {}
        ///     }
        /// </code>
        /// </example>
        /// <remarks>
        ///     This may be useful when emitting XML comments where the comment is static and should be readable in the
        ///     source code.
        /// </remarks>
        public FormattedStringBuilder AppendMultiline(string lines)
        {
            // Normalize to the builder's own newlines
            foreach (var line in lines.Split(["\r\n", "\n"], StringSplitOptions.None))
            {
                builder.AppendLine(line);
            }

            return builder;
        }

        /// <summary>
        ///     Appends a C# block with a <c>{</c>, an indented <paramref name="body"/>, and a <c>}</c> on the same
        ///     level as the opening curly bracket.
        /// </summary>
        /// <param name="body">The body contents.</param>
        /// <returns>A reference to this instance after the append operation has completed.</returns>
        /// <example>
        /// <code>
        ///     private string comment = new FormattedStringBuilder()
        ///         .AppendLine("if (value > 5)")
        ///         .AppendBlock(block => block
        ///             .AppendLine("value = value * 2 + 1;")
        ///          )
        ///         .AppendLine()
        ///         .AppendLine("else")
        ///         .AppendBlock(block => block
        ///             .AppendLine("value += 5;")
        ///          )
        ///         .ToString();
        /// </code>
        /// Would generate:
        /// <code>
        ///     if (value > 5)
        ///     {
        ///         value = value * 2 + 1;
        ///     }
        ///     else
        ///     {
        ///         value += 5;
        ///     }
        /// </code>
        /// </example>
        /// <remarks>
        ///     Consider nesting these as you'd nest regular blocks.
        /// </remarks>
        public FormattedStringBuilder AppendBlock(Action<FormattedStringBuilder> body)
        {
            if (body == null)
            {
                throw new ArgumentNullException(nameof(body));
            }

            builder.Append('{').Indent().AppendLine();
            body(builder);
            // User may have finished with an AppendLine(), so trim it
            return builder.TrimEnd().Unindent().AppendLine().Append('}');
        }

        /// <summary>
        ///     Appends the <paramref name="items"/>, writing <paramref name="separator"/> between them. Each element can be
        ///     rendered by <paramref name="appendElement"/>, which receives the builder and the item.
        /// </summary>
        /// <returns>A reference to this instance after the append operation has completed.</returns>
        /// <example>
        /// <code>
        ///     private readonly string[] modifiers = ["static", "extern", "new", "virtual", "abstract", "sealed", "override"]
        ///     private string allModifiers = new FormattedStringBuilder()
        ///         .AppendJoined(modifiers, " ", (b, i) => b.Append(i))
        ///         .ToString();
        /// </code>
        /// Would produce <c>"static extern new virtual abstract sealed override"</c>.
        /// </example>
        public FormattedStringBuilder AppendJoined<T>(
            IReadOnlyList<T> items,
            string separator,
            Action<FormattedStringBuilder, T> appendElement
        )
        {
            return builder.AppendJoined(items, 0, items.Count, separator, appendElement);
        }

        /// <summary>
        ///     Appends the <paramref name="items"/>, writing <paramref name="separator"/> between them. Each element can be
        ///     rendered by <paramref name="appendElement"/>, which receives the builder and the item.
        /// </summary>
        /// <returns>A reference to this instance after the append operation has completed.</returns>
        /// <example>
        /// <code>
        ///     private readonly string[] modifiers = ["static", "extern", "new", "virtual", "abstract", "sealed", "override"]
        ///     private string allModifiers = new FormattedStringBuilder()
        ///         .AppendJoined(modifiers, 1, 5, " ", (b, i) => b.Append(i))
        ///         .ToString();
        /// </code>
        /// Would produce <c>"extern new virtual abstract sealed"</c>.
        /// </example>
        public FormattedStringBuilder AppendJoined<T>(
            IReadOnlyList<T> items,
            int startIndex,
            int count,
            string separator,
            Action<FormattedStringBuilder, T> appendElement
        )
        {
            ValidateRange(startIndex, count, items.Count);
            for (var i = 0; i < count; i++)
            {
                if (i != 0)
                {
                    builder.Append(separator);
                }

                appendElement(builder, items[startIndex + i]);
            }

            return builder;
        }

        /// <summary>
        ///     Appends the <paramref name="items"/>, writing <paramref name="separator"/> between them. Each element can be
        ///     rendered by <paramref name="appendElement"/>, which receives the builder and the item.
        /// </summary>
        /// <returns>A reference to this instance after the append operation has completed.</returns>
        /// <example>
        /// <code>
        ///     private readonly string[] modifiers = ["static", "extern", "new", "virtual", "abstract", "sealed", "override"]
        ///     private string allModifiers = new FormattedStringBuilder()
        ///         .AppendJoined(modifiers, ' ', (b, i) => b.Append(i))
        ///         .ToString();
        /// </code>
        /// Would produce <c>"static extern new virtual abstract sealed override"</c>.
        /// </example>
        public FormattedStringBuilder AppendJoined<T>(
            IReadOnlyList<T> items,
            char separator,
            Action<FormattedStringBuilder, T> appendElement
        )
        {
            return builder.AppendJoined(items, 0, items.Count, separator, appendElement);
        }

        /// <summary>
        ///     Appends the <paramref name="items"/>, writing <paramref name="separator"/> between them. Each element can be
        ///     rendered by <paramref name="appendElement"/>, which receives the builder and the item.
        /// </summary>
        /// <returns>A reference to this instance after the append operation has completed.</returns>
        /// <example>
        /// <code>
        ///     private readonly string[] modifiers = ["static", "extern", "new", "virtual", "abstract", "sealed", "override"]
        ///     private string allModifiers = new FormattedStringBuilder()
        ///         .AppendJoined(modifiers, 1, 5, ' ', (b, i) => b.Append(i))
        ///         .ToString();
        /// </code>
        /// Would produce <c>"extern new virtual abstract sealed"</c>.
        /// </example>
        public FormattedStringBuilder AppendJoined<T>(
            IReadOnlyList<T> items,
            int startIndex,
            int count,
            char separator,
            Action<FormattedStringBuilder, T> appendElement
        )
        {
            ValidateRange(startIndex, count, items.Count);
            for (var i = 0; i < count; i++)
            {
                if (i != 0)
                {
                    builder.Append(separator);
                }

                appendElement(builder, items[startIndex + i]);
            }

            return builder;
        }

        /// <summary>
        ///     Appends the <paramref name="items"/>, writing <paramref name="separator"/> between them. Each element can be
        ///     rendered by <paramref name="appendElement"/>, which receives the builder and the item.
        /// </summary>
        /// <returns>A reference to this instance after the append operation has completed.</returns>
        /// <example>
        /// <code>
        ///     private readonly string[] modifiers = ["static", "extern", "new", "virtual", "abstract", "sealed", "override"]
        ///     private string allModifiers = new FormattedStringBuilder()
        ///         .AppendJoined(modifiers, " ", (b, i) => b.Append(i))
        ///         .ToString();
        /// </code>
        /// Would produce <c>"static extern new virtual abstract sealed override"</c>.
        /// </example>
        public FormattedStringBuilder AppendJoined<T>(
            ReadOnlySpan<T> items,
            string separator,
            Action<FormattedStringBuilder, T> appendElement
        )
        {
            return builder.AppendJoined(items, 0, items.Length, separator, appendElement);
        }

        /// <summary>
        ///     Appends the <paramref name="items"/>, writing <paramref name="separator"/> between them. Each element can be
        ///     rendered by <paramref name="appendElement"/>, which receives the builder and the item.
        /// </summary>
        /// <returns>A reference to this instance after the append operation has completed.</returns>
        /// <example>
        /// <code>
        ///     private readonly string[] modifiers = ["static", "extern", "new", "virtual", "abstract", "sealed", "override"]
        ///     private string allModifiers = new FormattedStringBuilder()
        ///         .AppendJoined(modifiers, 1, 5, " ", (b, i) => b.Append(i))
        ///         .ToString();
        /// </code>
        /// Would produce <c>"extern new virtual abstract sealed"</c>.
        /// </example>
        public FormattedStringBuilder AppendJoined<T>(
            ReadOnlySpan<T> items,
            int startIndex,
            int count,
            string separator,
            Action<FormattedStringBuilder, T> appendElement
        )
        {
            ValidateRange(startIndex, count, items.Length);
            for (var i = 0; i < count; i++)
            {
                if (i != 0)
                {
                    builder.Append(separator);
                }

                appendElement(builder, items[startIndex + i]);
            }

            return builder;
        }

        /// <summary>
        ///     Appends the <paramref name="items"/>, writing <paramref name="separator"/> between them. Each element can be
        ///     rendered by <paramref name="appendElement"/>, which receives the builder and the item.
        /// </summary>
        /// <returns>A reference to this instance after the append operation has completed.</returns>
        /// <example>
        /// <code>
        ///     private readonly string[] modifiers = ["static", "extern", "new", "virtual", "abstract", "sealed", "override"]
        ///     private string allModifiers = new FormattedStringBuilder()
        ///         .AppendJoined(modifiers, ' ', (b, i) => b.Append(i))
        ///         .ToString();
        /// </code>
        /// Would produce <c>"static extern new virtual abstract sealed override"</c>.
        /// </example>
        public FormattedStringBuilder AppendJoined<T>(
            ReadOnlySpan<T> items,
            char separator,
            Action<FormattedStringBuilder, T> appendElement
        )
        {
            return builder.AppendJoined(items, 0, items.Length, separator, appendElement);
        }

        /// <summary>
        ///     Appends the <paramref name="items"/>, writing <paramref name="separator"/> between them. Each element can be
        ///     rendered by <paramref name="appendElement"/>, which receives the builder and the item.
        /// </summary>
        /// <returns>A reference to this instance after the append operation has completed.</returns>
        /// <example>
        /// <code>
        ///     private readonly string[] modifiers = ["static", "extern", "new", "virtual", "abstract", "sealed", "override"]
        ///     private string allModifiers = new FormattedStringBuilder()
        ///         .AppendJoined(modifiers, 1, 5, ' ', (b, i) => b.Append(i))
        ///         .ToString();
        /// </code>
        /// Would produce <c>"extern new virtual abstract sealed"</c>.
        /// </example>
        public FormattedStringBuilder AppendJoined<T>(
            ReadOnlySpan<T> items,
            int startIndex,
            int count,
            char separator,
            Action<FormattedStringBuilder, T> appendElement
        )
        {
            ValidateRange(startIndex, count, items.Length);
            for (var i = 0; i < count; i++)
            {
                if (i != 0)
                {
                    builder.Append(separator);
                }

                appendElement(builder, items[startIndex + i]);
            }

            return builder;
        }

        // TODO: consider elevating this up to a public API
        private FormattedStringBuilder TrimEnd()
        {
            var length = builder.Length;
            while (length > 0 && char.IsWhiteSpace(builder[length - 1]))
            {
                length--;
            }

            builder.Length = length;
            return builder;
        }
    }

    private static void ValidateRange(int startIndex, int count, int length)
    {
        if (startIndex < 0)
        {
            throw new ArgumentOutOfRangeException(nameof(startIndex), startIndex, "Start must be non-negative");
        }
        if (count < 0)
        {
            throw new ArgumentOutOfRangeException(nameof(count), count, "Count must be non-negative");
        }
        if (length < count + startIndex)
        {
            throw new ArgumentOutOfRangeException(nameof(count), count + startIndex, $"There are only {length} items");
        }
    }
}
