// <auto-generated/>
#nullable enable
#pragma warning disable 0618, 1591, 8019

using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace EnumTests;

[global::Microsoft.CodeAnalysis.Embedded]
[global::System.CodeDom.Compiler.GeneratedCode("ZCrew.Extensions.CodeAnalysis.CSharp", "0.0.0.0")]
internal static class TestEnumSourceText
{
    public static readonly SourceText SourceText = SourceText.From(
        """
        namespace EnumTests;
        
        [Microsoft.CodeAnalysis.Embedded]
        public enum TestEnum
        {
            Foo,
            Bar,
            Baz,
        }
        
        """,
        Encoding.UTF8
    );
    
    public static void AddTestEnumDefinition(this IncrementalGeneratorPostInitializationContext context)
    {
        context.AddSource("EnumTests.TestEnum.g.cs", SourceText);
    }
}
