using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using ZCrew.Extensions.CodeAnalysis.CSharp.EmbeddedAttribute.Models;
using ZCrew.Extensions.CodeAnalysis.CSharp.Text;

namespace ZCrew.Extensions.CodeAnalysis.CSharp.EmbeddedAttribute.SourceGenerators;

internal static class ConstructorSourceGenerator
{
    private const string GeneratorAssemblyName = "ZCrew.Extensions.CodeAnalysis.CSharp";

    public static void Generate(SourceProductionContext context, EmbeddedAttributeGroup group)
    {
        var hintName = string.IsNullOrEmpty(group.Namespace)
            ? $"{group.BaseName}Constructor.g.cs"
            : $"{group.Namespace}.{group.BaseName}Constructor.g.cs";

        var source = GenerateSource(group);
        context.AddSource(hintName, SourceText.From(source, Encoding.UTF8));
    }

    private static string GenerateSource(EmbeddedAttributeGroup group)
    {
        var baseName = group.BaseName;
        var builderType = $"I{baseName}DataBuilder";
        var hasNamedParams = !group.UniqueNamedParameters.IsDefaultOrEmpty;
        var hasAnyGenericConstructors = HasGenericConstructors(group);
        var builder = new FormattedStringBuilder();

        builder
            .AppendLine("// <auto-generated/>")
            .AppendNullableEnable()
            .AppendCommonPragmaDisable()
            .AppendLine()
            .AppendFileScopedNamespaceDeclaration(group.Namespace)
            .AppendLine()
            .AppendGeneratedAttribute(GeneratorAssemblyName)
            .Append($"internal sealed class {baseName}Constructor")
            .AppendLine()
            .Append($"    : global::ZCrew.Extensions.CodeAnalysis.CSharp.AttributeConstructor<{builderType}>")
            .AppendLine()
            .Append('{')
            .Indent();

        // Generate static instances for each constructor
        for (var i = 0; i < group.AllConstructors.Count; i++)
        {
            var constructor = group.AllConstructors[i];
            var hasTypeParams = !constructor.TypeParameterNames.IsDefaultOrEmpty;

            builder.AppendLine().Append($"private static readonly {baseName}Constructor constructor{i} = new(");

            if (!hasTypeParams && constructor.Parameters.IsDefaultOrEmpty)
            {
                builder.Append("[]);");
            }
            else if (!hasTypeParams)
            {
                builder.Append('[').Indent();
                AppendParameterReferences(builder, baseName, constructor.Parameters);
                builder.Unindent().AppendLine().Append("]);");
            }
            else
            {
                builder.Indent();

                // Type parameters array
                builder.AppendLine().Append('[');
                AppendTypeParameterReferences(builder, baseName, constructor.TypeParameterNames);
                builder.Append("],");

                // Parameters array
                if (constructor.Parameters.IsDefaultOrEmpty)
                {
                    builder.AppendLine().Append("[]");
                }
                else
                {
                    builder.AppendLine().Append('[').Indent();
                    AppendParameterReferences(builder, baseName, constructor.Parameters);
                    builder.Unindent().AppendLine().Append(']');
                }

                builder.Unindent().AppendLine().Append(");");
            }

            builder.AppendLine();
        }

        // Generate Constructors array
        builder.Append($"private static readonly {baseName}Constructor[] Constructors =");

        if (group.AllConstructors.IsDefaultOrEmpty)
        {
            builder.Append(" [];");
        }
        else
        {
            builder.AppendLine().Append('[').Indent();
            for (var i = 0; i < group.AllConstructors.Count; i++)
            {
                builder.AppendLine().Append($"constructor{i}");
                if (i < group.AllConstructors.Count - 1)
                {
                    builder.Append(',');
                }
            }

            builder.Unindent().AppendLine().Append("];");
        }

        // Generate constructor overloads
        // Non-generic overload
        var baseCallNonGeneric = hasNamedParams
            ? $"base(parameters, {baseName}NamedParameter.NamedParameters)"
            : "base(parameters)";

        builder
            .AppendLine()
            .AppendLine()
            .Append($"public {baseName}Constructor(")
            .Indent()
            .AppendLine()
            .Append($"global::ZCrew.Extensions.CodeAnalysis.CSharp.AttributeParameter<{builderType}>[] parameters")
            .Unindent()
            .AppendLine()
            .Append($") : {baseCallNonGeneric} {{ }}");

        // Generic overload (only if any constructor uses type parameters)
        if (hasAnyGenericConstructors)
        {
            var baseCallGeneric = hasNamedParams
                ? $"base(typeParameters, parameters, {baseName}NamedParameter.NamedParameters)"
                : "base(typeParameters, parameters)";

            builder
                .AppendLine()
                .AppendLine()
                .Append($"public {baseName}Constructor(")
                .Indent()
                .AppendLine()
                .Append(
                    $"global::ZCrew.Extensions.CodeAnalysis.CSharp.AttributeTypeParameter<{builderType}>[] typeParameters,"
                )
                .AppendLine()
                .Append($"global::ZCrew.Extensions.CodeAnalysis.CSharp.AttributeParameter<{builderType}>[] parameters")
                .Unindent()
                .AppendLine()
                .Append($") : {baseCallGeneric} {{ }}");
        }

        // Generate WithAttributeData static method
        builder
            .AppendLine()
            .AppendLine()
            .Append(
                $"public static void WithAttributeData({builderType} builder, global::Microsoft.CodeAnalysis.AttributeData attributeData, global::Microsoft.CodeAnalysis.ISymbol targetSymbol)"
            )
            .AppendLine()
            .Append('{')
            .Indent()
            .AppendLine()
            .Append("builder.ForSymbol(targetSymbol);")
            .AppendLine()
            .Append("foreach (var constructor in Constructors)")
            .AppendLine()
            .Append('{')
            .Indent()
            .AppendLine()
            .Append("if (constructor.IsCalledBy(attributeData))")
            .AppendLine()
            .Append('{')
            .Indent()
            .AppendLine()
            .Append("constructor.Accept(builder, attributeData);")
            .AppendLine()
            .Append("return;")
            .Unindent()
            .AppendLine()
            .Append('}')
            .Unindent()
            .AppendLine()
            .Append('}')
            .Unindent()
            .AppendLine()
            .Append('}');

        builder.Unindent().AppendLine().Append('}').AppendLine();

        return builder.ToString();
    }

    private static bool HasGenericConstructors(EmbeddedAttributeGroup group)
    {
        foreach (var constructor in group.AllConstructors)
        {
            if (!constructor.TypeParameterNames.IsDefaultOrEmpty)
            {
                return true;
            }
        }

        return false;
    }

    private static void AppendParameterReferences(
        FormattedStringBuilder builder,
        string baseName,
        Collections.EquatableArray<EmbeddedParameterInfo> parameters
    )
    {
        for (var i = 0; i < parameters.Count; i++)
        {
            var pascalName = NamingHelper.ToPascalCase(parameters[i].Name);
            builder.AppendLine().Append($"{baseName}Parameter.{pascalName},");
        }
    }

    private static void AppendTypeParameterReferences(
        FormattedStringBuilder builder,
        string baseName,
        Collections.EquatableArray<string> typeParameterNames
    )
    {
        for (var i = 0; i < typeParameterNames.Count; i++)
        {
            if (i > 0)
            {
                builder.Append(", ");
            }

            var strippedName = NamingHelper.StripTypeParameterPrefix(typeParameterNames[i]);
            builder.Append($"{baseName}TypeParameter.{strippedName}");
        }
    }
}
