using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using ZCrew.Extensions.CodeAnalysis.CSharp.EmbeddedAttribute.Models;
using ZCrew.Extensions.CodeAnalysis.CSharp.Text;

namespace ZCrew.Extensions.CodeAnalysis.CSharp.EmbeddedAttribute.SourceGenerators;

internal static class DataBuilderInterfaceSourceGenerator
{
    private const string GeneratorAssemblyName = "ZCrew.Extensions.CodeAnalysis.CSharp";

    public static void Generate(SourceProductionContext context, EmbeddedAttributeGroup group)
    {
        var hintName = string.IsNullOrEmpty(group.Namespace)
            ? $"I{group.BaseName}DataBuilder.g.cs"
            : $"{group.Namespace}.I{group.BaseName}DataBuilder.g.cs";

        var source = GenerateSource(group);
        context.AddSource(hintName, SourceText.From(source, Encoding.UTF8));
    }

    private static string GenerateSource(EmbeddedAttributeGroup group)
    {
        var builder = new FormattedStringBuilder();

        builder
            .AppendAutoGeneratedComment()
            .AppendNullableEnable()
            .AppendCommonPragmaDisable()
            .AppendLine()
            .AppendFileScopedNamespaceDeclaration(group.Namespace)
            .AppendLine()
            .AppendEmbeddedAttribute()
            .AppendGeneratedAttribute(GeneratorAssemblyName)
            .Append($"internal interface I{group.BaseName}DataBuilder")
            .AppendLine()
            .Append('{')
            .Indent();

        // Track generated method signatures to avoid duplicates
        var generatedSignatures = new HashSet<string>();

        // Target ISymbol (where the attribute is located): void ForSymbol(ISymbol symbol)
        generatedSignatures.Add("ForSymbol(ISymbol)");
        builder.AppendLine().Append("void ForSymbol(global::Microsoft.CodeAnalysis.ISymbol symbol);");

        // Constructor parameters: void With{PascalName}(TypedConstant constant)
        foreach (var param in group.UniqueParameters)
        {
            var pascalName = NamingHelper.ToPascalCase(param.Name);
            var signature = $"With{pascalName}(TypedConstant)";
            if (generatedSignatures.Add(signature))
            {
                builder
                    .AppendLine()
                    .Append($"void With{pascalName}(global::Microsoft.CodeAnalysis.TypedConstant constant);");
            }
        }

        // Type parameters: void With{StrippedName}(ITypeSymbol symbol)
        foreach (var typeParam in group.UniqueTypeParameters)
        {
            var strippedName = NamingHelper.StripTypeParameterPrefix(typeParam.Name);
            var signature = $"With{strippedName}(ITypeSymbol)";
            if (generatedSignatures.Add(signature))
            {
                builder
                    .AppendLine()
                    .Append($"void With{strippedName}(global::Microsoft.CodeAnalysis.ITypeSymbol symbol);");
            }
        }

        // Named parameters: void With{PropertyName}(TypedConstant constant)
        foreach (var namedParam in group.UniqueNamedParameters)
        {
            var signature = $"With{namedParam.Name}(TypedConstant)";
            if (generatedSignatures.Add(signature))
            {
                builder
                    .AppendLine()
                    .Append($"void With{namedParam.Name}(global::Microsoft.CodeAnalysis.TypedConstant constant);");
            }
        }

        builder.Unindent().AppendLine().Append('}').AppendLine();

        return builder.ToString();
    }
}
