using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using ZCrew.Extensions.CodeAnalysis.CSharp.EmbeddedAttribute.Models;
using ZCrew.Extensions.CodeAnalysis.CSharp.Text;

namespace ZCrew.Extensions.CodeAnalysis.CSharp.EmbeddedAttribute.SourceGenerators;

internal static class NamedParameterSourceGenerator
{
    private const string GeneratorAssemblyName = "ZCrew.Extensions.CodeAnalysis.CSharp";

    public static void Generate(SourceProductionContext context, EmbeddedAttributeGroup group)
    {
        var hintName = string.IsNullOrEmpty(group.Namespace)
            ? $"{group.BaseName}NamedParameter.g.cs"
            : $"{group.Namespace}.{group.BaseName}NamedParameter.g.cs";

        var source = GenerateSource(group);
        context.AddSource(hintName, SourceText.From(source, Encoding.UTF8));
    }

    private static string GenerateSource(EmbeddedAttributeGroup group)
    {
        var baseName = group.BaseName;
        var builderType = $"I{baseName}DataBuilder";
        var builder = new FormattedStringBuilder();

        builder
            .AppendAutoGeneratedComment()
            .AppendNullableEnable()
            .AppendCommonPragmaDisable()
            .AppendLine()
            .AppendFileScopedNamespaceDeclaration(group.Namespace)
            .AppendLine()
            .AppendGeneratedAttribute(GeneratorAssemblyName)
            .Append($"internal sealed class {baseName}NamedParameter")
            .AppendLine()
            .Append($"    : global::ZCrew.Extensions.CodeAnalysis.CSharp.AttributeNamedParameter<{builderType}>")
            .AppendLine()
            .Append('{')
            .Indent();

        // Generate private static readonly fields for each named parameter
        foreach (var namedParam in group.UniqueNamedParameters)
        {
            var camelName = NamingHelper.ToCamelCase(namedParam.Name);
            builder
                .AppendLine()
                .Append($"private static readonly {baseName}NamedParameter {camelName} = new(")
                .Indent()
                .AppendLine()
                .Append($"\"{namedParam.Name}\",")
                .AppendLine()
                .Append($"(builder, _, constant) => builder.With{namedParam.Name}(constant)")
                .Unindent()
                .AppendLine()
                .Append(");");
        }

        // Generate NamedParameters array
        builder.AppendLine().AppendLine();
        builder.Append(
            $"internal static readonly global::ZCrew.Extensions.CodeAnalysis.CSharp.AttributeNamedParameter<{builderType}>[] NamedParameters ="
        );

        if (group.UniqueNamedParameters.IsDefaultOrEmpty)
        {
            builder.Append(" [];");
        }
        else
        {
            builder.AppendLine().Append('[').Indent();
            for (var i = 0; i < group.UniqueNamedParameters.Count; i++)
            {
                var camelName = NamingHelper.ToCamelCase(group.UniqueNamedParameters[i].Name);
                builder.AppendLine().Append(camelName);
                if (i < group.UniqueNamedParameters.Count - 1)
                {
                    builder.Append(',');
                }
            }

            builder.Unindent().AppendLine().Append("];");
        }

        // Generate constructor
        builder
            .AppendLine()
            .AppendLine()
            .Append($"public {baseName}NamedParameter(")
            .Indent()
            .AppendLine()
            .Append("string name,")
            .AppendLine()
            .Append(
                $"global::System.Action<{builderType}, string, global::Microsoft.CodeAnalysis.TypedConstant> valueAction"
            )
            .Unindent()
            .AppendLine()
            .Append(") : base(name, valueAction) { }");

        builder.Unindent().AppendLine().Append('}').AppendLine();

        return builder.ToString();
    }
}
