using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using ZCrew.Extensions.CodeAnalysis.CSharp.EmbeddedAttribute.Models;
using ZCrew.Extensions.CodeAnalysis.CSharp.Text;

namespace ZCrew.Extensions.CodeAnalysis.CSharp.EmbeddedAttribute.SourceGenerators;

internal static class SourceTextSourceGenerator
{
    private const string GeneratorAssemblyName = "ZCrew.Extensions.CodeAnalysis.CSharp";

    public static void Generate(SourceProductionContext context, EmbeddedAttributeGroup group)
    {
        var hintName = string.IsNullOrEmpty(group.Namespace)
            ? $"{group.BaseName}SourceText.g.cs"
            : $"{group.Namespace}.{group.BaseName}SourceText.g.cs";

        var source = GenerateSource(group);
        context.AddSource(hintName, SourceText.From(source, Encoding.UTF8));
    }

    private static string GenerateSource(EmbeddedAttributeGroup group)
    {
        var builder = new FormattedStringBuilder();

        builder
            .AppendLine("// <auto-generated/>")
            .AppendNullableEnable()
            .AppendCommonPragmaDisable()
            .AppendLine()
            .AppendLine("using System.Text;")
            .AppendLine("using Microsoft.CodeAnalysis.Text;")
            .AppendLine()
            .AppendFileScopedNamespaceDeclaration(group.Namespace)
            .AppendLine()
            .AppendGeneratedAttribute(GeneratorAssemblyName)
            .Append($"internal static class {group.BaseName}SourceText")
            .AppendLine()
            .Append('{')
            .Indent()
            .AppendLine()
            .Append("public static readonly SourceText SourceText = SourceText.From(")
            .Indent()
            .AppendLine()
            .AppendRawString(group.CombinedSourceText)
            .Append(',')
            .AppendLine()
            .Append("Encoding.UTF8")
            .Unindent()
            .AppendLine()
            .Append(");")
            .Unindent()
            .AppendLine()
            .Append('}')
            .AppendLine();

        return builder.ToString();
    }
}
