using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using ZCrew.Extensions.CodeAnalysis.CSharp.EmbeddedAttribute.Models;
using ZCrew.Extensions.CodeAnalysis.CSharp.Text;

namespace ZCrew.Extensions.CodeAnalysis.CSharp.EmbeddedAttribute.SourceGenerators;

internal static class TypeParameterSourceGenerator
{
    private const string GeneratorAssemblyName = "ZCrew.Extensions.CodeAnalysis.CSharp";

    public static void Generate(SourceProductionContext context, EmbeddedAttributeGroup group)
    {
        var hintName = string.IsNullOrEmpty(group.Namespace)
            ? $"{group.BaseName}TypeParameter.g.cs"
            : $"{group.Namespace}.{group.BaseName}TypeParameter.g.cs";

        var source = GenerateSource(group);
        context.AddSource(hintName, SourceText.From(source, Encoding.UTF8));
    }

    private static string GenerateSource(EmbeddedAttributeGroup group)
    {
        var baseName = group.BaseName;
        var builderType = $"I{baseName}DataBuilder";
        var builder = new FormattedStringBuilder();

        builder
            .AppendLine("// <auto-generated/>")
            .AppendNullableEnable()
            .AppendCommonPragmaDisable()
            .AppendLine()
            .AppendFileScopedNamespaceDeclaration(group.Namespace)
            .AppendLine()
            .AppendGeneratedAttribute(GeneratorAssemblyName)
            .Append($"internal sealed class {baseName}TypeParameter")
            .AppendLine()
            .Append($"    : global::ZCrew.Extensions.CodeAnalysis.CSharp.AttributeTypeParameter<{builderType}>")
            .AppendLine()
            .Append('{')
            .Indent();

        // Generate static readonly fields for each unique type parameter
        foreach (var typeParam in group.UniqueTypeParameters)
        {
            var strippedName = NamingHelper.StripTypeParameterPrefix(typeParam.Name);
            builder
                .AppendLine()
                .Append($"public static readonly {baseName}TypeParameter {strippedName} = new(")
                .Indent()
                .AppendLine()
                .Append($"(builder, symbol) => builder.With{strippedName}(symbol)")
                .Unindent()
                .AppendLine()
                .Append(");");
        }

        // Generate constructor
        builder
            .AppendLine()
            .AppendLine()
            .Append($"public {baseName}TypeParameter(")
            .Indent()
            .AppendLine()
            .Append($"global::System.Action<{builderType}, global::Microsoft.CodeAnalysis.ITypeSymbol> valueAction")
            .Unindent()
            .AppendLine()
            .Append(") : base(valueAction) { }");

        builder.Unindent().AppendLine().Append('}').AppendLine();

        return builder.ToString();
    }
}
