// <auto-generated/>
#nullable enable
#pragma warning disable 0618, 1591, 8019

namespace CombinedTests;

[global::Microsoft.CodeAnalysis.Embedded]
[global::System.CodeDom.Compiler.GeneratedCode("ZCrew.Extensions.CodeAnalysis.CSharp", "0.0.0.0")]
internal static partial class TestEnumSourceText
{
    public static readonly global::Microsoft.CodeAnalysis.Text.SourceText SourceText = global::Microsoft.CodeAnalysis.Text.SourceText.From(
        """
        namespace CombinedTests;
        
        [Microsoft.CodeAnalysis.Embedded]
        public enum TestEnum
        {
            Foo,
            Bar,
        }
        
        """,
        global::System.Text.Encoding.UTF8
    );
    
    public static void AddTestEnumDefinition(this global::Microsoft.CodeAnalysis.IncrementalGeneratorPostInitializationContext context)
    {
        context.AddSource("CombinedTests.TestEnumSourceText.g.cs", SourceText);
    }
}
