// <auto-generated/>
#nullable enable
#pragma warning disable 0618, 1591, 8019

using System.Text;
using Microsoft.CodeAnalysis.Text;

namespace CacheTests;

[global::System.CodeDom.Compiler.GeneratedCode("ZCrew.Extensions.CodeAnalysis.CSharp", "0.0.0.0")]
internal static class TestEnumSourceText
{
    public static readonly SourceText SourceText = SourceText.From(
        """
        namespace CacheTests;
        
        [Microsoft.CodeAnalysis.Embedded]
        public enum TestEnum
        {
            Foo,
            Bar,
            Baz,
        }
        
        """,
        Encoding.UTF8
    );
}
