using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using ZCrew.Extensions.CodeAnalysis.CSharp.IsType.Models;
using ZCrew.Extensions.CodeAnalysis.CSharp.Text;

namespace ZCrew.Extensions.CodeAnalysis.CSharp.IsType.SourceGenerators;

/// <summary>
///     Emits the implementing partial method for an <see cref="IsTypeMethodInfo"/>: the shared scaffolding plus the
///     composed implementation's <c>is</c> pattern.
/// </summary>
internal static class IsTypeMethodSourceGenerator
{
    /// <summary>
    ///     Emits the implementing partial method: the shared scaffolding plus the composed implementation's
    ///     <c>is</c> pattern.
    /// </summary>
    /// <param name="context">The source production context.</param>
    /// <param name="info">The method metadata to emit.</param>
    public static void Generate(SourceProductionContext context, IsTypeMethodInfo info)
    {
        var builder = new FormattedStringBuilder();

        builder
            .AppendAutoGeneratedComment()
            .AppendNullableEnable()
            .AppendCommonPragmaDisable()
            .AppendLine()
            .AppendFileScopedNamespaceDeclaration(info.Namespace);

        if (!string.IsNullOrEmpty(info.Namespace))
        {
            builder.AppendLine();
        }

        // Re-open the containing type(s), outermost-first.
        foreach (var declaration in info.ContainingTypeDeclarations)
        {
            builder.Append(declaration).AppendLine().Append('{').Indent().AppendLine();
        }

        // The implementing method as an expression body; the implementation supplies everything after the " =>".
        builder.Append(info.MethodSignature).Append(" =>").Indent().AppendLine();
        info.Implementation.AppendImplementation(builder);
        builder.Unindent();

        // Close the containing type(s).
        for (var i = 0; i < info.ContainingTypeDeclarations.Count; i++)
        {
            builder.Unindent().AppendLine().Append('}');
        }

        builder.AppendLine();

        context.AddSource(info.HintName, SourceText.From(builder.ToString(), Encoding.UTF8));
    }
}
