// <auto-generated/>
#nullable enable
#pragma warning disable 0618, 1591, 8019

namespace IsTypeTests;

partial class SymbolChecks
{
    public static partial bool IsInner([global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] global::Microsoft.CodeAnalysis.ISymbol? symbol) =>
        symbol is global::Microsoft.CodeAnalysis.INamedTypeSymbol
        {
            Name: "Inner",
            Arity: 0,
            ContainingType:
            {
                Name: "Outer",
                Arity: 0,
                ContainingType: null,
                ContainingNamespace:
                {
                    Name: "Dependable",
                    ContainingNamespace: { Name: "ZCrew", ContainingNamespace.IsGlobalNamespace: true }
                }
            }
        };
}
