using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace ZCrew.Extensions.CodeAnalysis.CSharp.Testing;

/// <summary>
///     A file generated by an <see cref="IIncrementalGenerator"/> or <see cref="ISourceGenerator"/>.
/// </summary>
public record GeneratedSource
{
    /// <summary>
    ///     Initializes a new <see cref="GeneratedSource"/>.
    /// </summary>
    /// <param name="fileName">The source file name.</param>
    /// <param name="content">The content of the file.</param>
    public GeneratedSource(string fileName, SourceText content)
    {
        FileName = fileName;
        Content = content;
    }

    /// <summary>
    ///     Initializes a new <see cref="GeneratedSource"/>.
    /// </summary>
    /// <param name="generatorType">The generator type, used to get the full file name.</param>
    /// <param name="hintName">The source hint name.</param>
    /// <param name="content">The content of the file.</param>
    public GeneratedSource(Type generatorType, string hintName, SourceText content)
        : this(GetDirectory(generatorType) / hintName, content) { }

    /// <summary>
    ///     Initializes a new <see cref="GeneratedSource"/>.
    /// </summary>
    /// <param name="generatorType">The generator type, used to get the full file name.</param>
    /// <param name="result">The generated result from a run.</param>
    internal GeneratedSource(Type generatorType, GeneratedSourceResult result)
        : this(generatorType, result.HintName, result.SourceText) { }

    /// <summary>
    ///     The file name.
    /// </summary>
    public string FileName { get; }

    /// <summary>
    ///     The generated content.
    /// </summary>
    public SourceText Content { get; }

    /// <summary>
    ///     The directory Roslyn writes a generator's sources into: the generator's assembly name followed by its full
    ///     type name.
    /// </summary>
    /// <param name="generatorType">The generator type.</param>
    /// <returns>The directory the generator's hint names are resolved against.</returns>
    internal static TestPath GetDirectory(Type generatorType)
    {
        return TestPath.Empty / generatorType.Assembly.GetName().Name / generatorType.FullName;
    }
}
