// <auto-generated/>
#nullable enable
#pragma warning disable 0618, 1591, 8019

namespace AttributeTests;

[global::System.CodeDom.Compiler.GeneratedCode("ZCrew.Extensions.CodeAnalysis.CSharp", "0.0.0.0")]
internal sealed class TestAttributeConstructor
    : global::ZCrew.Extensions.CodeAnalysis.CSharp.AttributeConstructor<ITestAttributeDataBuilder>
{
    private static readonly TestAttributeConstructor constructor0 = new(
        [TestAttributeTypeParameter.Service, TestAttributeTypeParameter.Implementation],
        [
            TestAttributeParameter.Name,
            TestAttributeParameter.Value,
        ]
    );
    private static readonly TestAttributeConstructor[] Constructors =
    [
        constructor0
    ];
    
    public TestAttributeConstructor(
        global::ZCrew.Extensions.CodeAnalysis.CSharp.AttributeParameter<ITestAttributeDataBuilder>[] parameters
    ) : base(parameters, TestAttributeNamedParameter.NamedParameters) { }
    
    public TestAttributeConstructor(
        global::ZCrew.Extensions.CodeAnalysis.CSharp.AttributeTypeParameter<ITestAttributeDataBuilder>[] typeParameters,
        global::ZCrew.Extensions.CodeAnalysis.CSharp.AttributeParameter<ITestAttributeDataBuilder>[] parameters
    ) : base(typeParameters, parameters, TestAttributeNamedParameter.NamedParameters) { }
    
    public static void WithAttributeData(ITestAttributeDataBuilder builder, global::Microsoft.CodeAnalysis.AttributeData attributeData, global::Microsoft.CodeAnalysis.ISymbol targetSymbol)
    {
        builder.ForSymbol(targetSymbol);
        foreach (var constructor in Constructors)
        {
            if (constructor.IsCalledBy(attributeData))
            {
                constructor.Accept(builder, attributeData);
                return;
            }
        }
    }
}
