// <auto-generated/>
#nullable enable
#pragma warning disable 0618, 1591, 8019

namespace AttributeTests;

[global::System.CodeDom.Compiler.GeneratedCode("ZCrew.Extensions.CodeAnalysis.CSharp", "0.0.0.0")]
internal class TestAttributeParameter
    : global::ZCrew.Extensions.CodeAnalysis.CSharp.AttributeParameter<ITestAttributeDataBuilder>
{
    public static readonly TestAttributeParameter Name = new(
        "System.String",
        (builder, constant) => builder.WithName(constant)
    );
    public static readonly TestAttributeParameter Value = new(
        "System.Int32",
        (builder, constant) => builder.WithValue(constant)
    );
    
    public TestAttributeParameter(
        string type,
        global::System.Action<ITestAttributeDataBuilder, global::Microsoft.CodeAnalysis.TypedConstant> valueAction
    ) : base(type, valueAction) { }
}
