// <auto-generated/>
#nullable enable
#pragma warning disable 0618, 1591, 8019

namespace AttributeTests;

[global::Microsoft.CodeAnalysis.Embedded]
[global::System.CodeDom.Compiler.GeneratedCode("ZCrew.Extensions.CodeAnalysis.CSharp", "0.0.0.0")]
internal sealed class TestAttributeNamedParameter
    : global::ZCrew.Extensions.CodeAnalysis.CSharp.AttributeNamedParameter<ITestAttributeDataBuilder>
{
    private static readonly TestAttributeNamedParameter foo = new(
        "Foo",
        (builder, _, constant) => builder.WithFoo(constant)
    );
    private static readonly TestAttributeNamedParameter bar = new(
        "Bar",
        (builder, _, constant) => builder.WithBar(constant)
    );
    
    internal static readonly global::ZCrew.Extensions.CodeAnalysis.CSharp.AttributeNamedParameter<ITestAttributeDataBuilder>[] NamedParameters =
    [
        foo,
        bar
    ];
    
    public TestAttributeNamedParameter(
        string name,
        global::System.Action<ITestAttributeDataBuilder, string, global::Microsoft.CodeAnalysis.TypedConstant> valueAction
    ) : base(name, valueAction) { }
}
