// <auto-generated/>
#nullable enable
#pragma warning disable 0618, 1591, 8019

using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace AttributeTests;

[global::System.CodeDom.Compiler.GeneratedCode("ZCrew.Extensions.CodeAnalysis.CSharp", "0.0.0.0")]
internal static class TestAttributeSourceText
{
    public static readonly SourceText SourceText = SourceText.From(
        """
        using System;
        
        namespace AttributeTests;
        
        [Microsoft.CodeAnalysis.Embedded]
        public class TestAttribute<TService, TImplementation> : Attribute
        {
            public TestAttribute(string name, int value) { }
        
            public string Foo { get; init; }
            public string Bar { get; init; }
        }
        
        """,
        Encoding.UTF8
    );
    
    public static void AddTestAttributeDefinition(this IncrementalGeneratorPostInitializationContext context)
    {
        context.AddSource("AttributeTests.TestAttribute.g.cs", SourceText);
    }
}
