// <auto-generated/>
#nullable enable
#pragma warning disable 0618, 1591, 8019

namespace AttributeTests;

[global::System.CodeDom.Compiler.GeneratedCode("ZCrew.Extensions.CodeAnalysis.CSharp", "0.0.0.0")]
internal sealed class TestAttributeTypeParameter
    : global::ZCrew.Extensions.CodeAnalysis.CSharp.AttributeTypeParameter<ITestAttributeDataBuilder>
{
    public static readonly TestAttributeTypeParameter Service = new(
        (builder, symbol) => builder.WithService(symbol)
    );
    public static readonly TestAttributeTypeParameter Implementation = new(
        (builder, symbol) => builder.WithImplementation(symbol)
    );
    
    public TestAttributeTypeParameter(
        global::System.Action<ITestAttributeDataBuilder, global::Microsoft.CodeAnalysis.ITypeSymbol> valueAction
    ) : base(valueAction) { }
}
