// <auto-generated/>
#nullable enable
#pragma warning disable 0618, 1591, 8019

namespace AttributeTests;

/// <summary>
///     Attribute data for <see cref="TestAttribute"/>.
/// </summary>
[global::Microsoft.CodeAnalysis.Embedded]
[global::System.CodeDom.Compiler.GeneratedCode("ZCrew.Extensions.CodeAnalysis.CSharp", "0.0.0.0")]
internal partial record TestAttributeData
{
    public global::Microsoft.CodeAnalysis.ITypeSymbol ServiceType = null!;
    public global::Microsoft.CodeAnalysis.ITypeSymbol? ImplementationType;
    public global::System.Collections.Immutable.ImmutableArray<string> Tags = global::System.Collections.Immutable.ImmutableArray<string>.Empty;
}
internal static partial class AttributeDataExtensions
{
    public static bool TryGetTestAttributeData(this global::Microsoft.CodeAnalysis.AttributeData attributeData, [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] out TestAttributeData? data)
    {
        foreach (var constructor in TestAttributeDataConstructor.TestAttributeDataConstructors)
        {
            if (constructor.TryCreateAttributeFor(attributeData, out data))
            {
                return true;
            }
        }
        data = default;
        return false;
    }
}
internal static partial class SyntaxValueProviderExtensions
{
    public static global::Microsoft.CodeAnalysis.IncrementalValuesProvider<T> ForTestAttributeData<T>(this global::Microsoft.CodeAnalysis.SyntaxValueProvider syntaxProvider, global::System.Func<global::Microsoft.CodeAnalysis.SyntaxNode, global::System.Threading.CancellationToken, bool> predicate, global::System.Func<global::Microsoft.CodeAnalysis.GeneratorAttributeSyntaxContext, global::System.Collections.Immutable.ImmutableArray<TestAttributeData>, global::System.Threading.CancellationToken, T> transform)
    {
        var results = syntaxProvider.ForAttributeWithMetadataName(
            "AttributeTests.TestAttribute",
            predicate,
            (context, cancellationToken) =>
            {
                var builder = global::System.Collections.Immutable.ImmutableArray.CreateBuilder<TestAttributeData>(context.Attributes.Length);
                foreach (var attribute in context.Attributes)
                {
                    cancellationToken.ThrowIfCancellationRequested();
                    if (attribute.TryGetTestAttributeData(out var data))
                    {
                        builder.Add(data);
                    }
                }
                if (builder.Count == 0)
                {
                    return (Value: default(T)!, IsMatch: false);
                }
                return (Value: transform(context, builder.ToImmutable(), cancellationToken), IsMatch: true);
            });
        var matches = global::Microsoft.CodeAnalysis.IncrementalValueProviderExtensions.Where(results, result => result.IsMatch);
        return global::Microsoft.CodeAnalysis.IncrementalValueProviderExtensions.Select(matches, (result, _) => result.Value);
    }
}
file sealed class TestAttributeDataConstructor : global::ZCrew.Extensions.CodeAnalysis.CSharp.AttributeConstructor<TestAttributeData>
{
    private static readonly TestAttributeDataConstructor constructor0 = new([TestAttributeDataParameter.ServiceType]);
    private static readonly TestAttributeDataConstructor constructor1 = new([TestAttributeDataParameter.ServiceType, TestAttributeDataParameter.ImplementationType, TestAttributeDataParameter.Tags]);
    public static readonly TestAttributeDataConstructor[] TestAttributeDataConstructors = [constructor0, constructor1];
    protected override string AttributeMetadataName => "AttributeTests.TestAttribute";
    public TestAttributeDataConstructor(global::ZCrew.Extensions.CodeAnalysis.CSharp.AttributeParameter<TestAttributeData>[] parameters) : base([], parameters, []) { }
}
file sealed class TestAttributeDataParameter : global::ZCrew.Extensions.CodeAnalysis.CSharp.AttributeParameter<TestAttributeData>
{
    public static readonly TestAttributeDataParameter ServiceType = new("System.Type", (model, constant) => global::ZCrew.Extensions.CodeAnalysis.CSharp.TypedConstantExtensions.GetValue(constant, out model.ServiceType));
    public static readonly TestAttributeDataParameter ImplementationType = new("System.Type", (model, constant) => global::ZCrew.Extensions.CodeAnalysis.CSharp.TypedConstantExtensions.GetValue(constant, out model.ImplementationType));
    public static readonly TestAttributeDataParameter Tags = new("string[]", (model, constant) => global::ZCrew.Extensions.CodeAnalysis.CSharp.TypedConstantExtensions.GetValue(constant, out model.Tags));
    public TestAttributeDataParameter(string type, global::System.Action<TestAttributeData, global::Microsoft.CodeAnalysis.TypedConstant> valueAction) : base(type, valueAction) { }
}
