// <auto-generated/>
#nullable enable
#pragma warning disable 0618, 1591, 8019

namespace AttributeTests;

[global::Microsoft.CodeAnalysis.Embedded]
[global::System.CodeDom.Compiler.GeneratedCode("ZCrew.Extensions.CodeAnalysis.CSharp", "0.0.0.0")]
internal static partial class TestAttributeSourceText
{
    public static readonly global::Microsoft.CodeAnalysis.Text.SourceText SourceText = global::Microsoft.CodeAnalysis.Text.SourceText.From(
        """
        using System;
        
        namespace AttributeTests;
        
        // 'System.Type' maps to ITypeSymbol and follows the reference-type rules; an array maps to the ImmutableArray<T>
        // value type and is left alone even though only one constructor declares it
        [Microsoft.CodeAnalysis.Embedded]
        public class TestAttribute : Attribute
        {
            public TestAttribute(Type serviceType) { }
        
            public TestAttribute(Type serviceType, Type implementationType, string[] tags) { }
        }
        
        """,
        global::System.Text.Encoding.UTF8
    );
    
    public static void AddTestAttributeDefinition(this global::Microsoft.CodeAnalysis.IncrementalGeneratorPostInitializationContext context)
    {
        context.AddSource("AttributeTests.TestAttributeSourceText.g.cs", SourceText);
    }
}
