// <auto-generated/>
#nullable enable
#pragma warning disable 0618, 1591, 8019

namespace AttributeTests;

[global::Microsoft.CodeAnalysis.Embedded]
[global::System.CodeDom.Compiler.GeneratedCode("ZCrew.Extensions.CodeAnalysis.CSharp", "0.0.0.0")]
internal static partial class TestAttributeSourceText_2
{
    public static readonly global::Microsoft.CodeAnalysis.Text.SourceText SourceText = global::Microsoft.CodeAnalysis.Text.SourceText.From(
        """
        using System;
        
        namespace AttributeTests;
        
        [Microsoft.CodeAnalysis.Embedded]
        public class TestAttribute<TService, TImplementation> : Attribute { }
        
        """,
        global::System.Text.Encoding.UTF8
    );
    
    public static void AddTestAttribute_2_Definition(this global::Microsoft.CodeAnalysis.IncrementalGeneratorPostInitializationContext context)
    {
        context.AddSource("AttributeTests.TestAttributeSourceText_2.g.cs", SourceText);
    }
}
