// <auto-generated/>
#nullable enable
#pragma warning disable 0618, 1591, 8019

using System.Text;
using Microsoft.CodeAnalysis.Text;

namespace AttributeTests;

[global::System.CodeDom.Compiler.GeneratedCode("ZCrew.Extensions.CodeAnalysis.CSharp", "0.0.0.0")]
internal static class TestAttributeSourceText
{
    public static readonly SourceText SourceText = SourceText.From(
        """
        using System;
        
        namespace AttributeTests;
        
        [Microsoft.CodeAnalysis.Embedded]
        public class TestAttribute : Attribute
        {
            public TestAttribute() { }
        
            public TestAttribute(string name) { }
        
            public TestAttribute(string name, int value) { }
        }
        
        """,
        Encoding.UTF8
    );
}
