// <auto-generated/>
#nullable enable
#pragma warning disable 0618, 1591, 8019

namespace AttributeTests;

/// <summary>
///     Attribute data for <see cref="TestAttribute"/>.
/// </summary>
[global::Microsoft.CodeAnalysis.Embedded]
[global::System.CodeDom.Compiler.GeneratedCode("ZCrew.Extensions.CodeAnalysis.CSharp", "0.0.0.0")]
internal partial record TestAttributeData
{
    public string Matches = null!;
    public string EqualsString = null!;
    public string ToStringString = null!;
    public object? ToStringObject;
    public string? GetHashCodeString;
}
internal static partial class AttributeDataExtensions
{
    public static bool TryGetTestAttributeData(this global::Microsoft.CodeAnalysis.AttributeData attributeData, [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] out TestAttributeData? data)
    {
        foreach (var constructor in TestAttributeDataConstructor.TestAttributeDataConstructors)
        {
            if (constructor.TryCreateAttributeFor(attributeData, out data))
            {
                return true;
            }
        }
        data = default;
        return false;
    }
}
internal static partial class SyntaxValueProviderExtensions
{
    public static global::Microsoft.CodeAnalysis.IncrementalValuesProvider<T> ForTestAttributeData<T>(this global::Microsoft.CodeAnalysis.SyntaxValueProvider syntaxProvider, global::System.Func<global::Microsoft.CodeAnalysis.SyntaxNode, global::System.Threading.CancellationToken, bool> predicate, global::System.Func<global::Microsoft.CodeAnalysis.GeneratorAttributeSyntaxContext, global::System.Collections.Immutable.ImmutableArray<TestAttributeData>, global::System.Threading.CancellationToken, T> transform)
    {
        var results = syntaxProvider.ForAttributeWithMetadataName(
            "AttributeTests.TestAttribute",
            predicate,
            (context, cancellationToken) =>
            {
                var builder = global::System.Collections.Immutable.ImmutableArray.CreateBuilder<TestAttributeData>(context.Attributes.Length);
                foreach (var attribute in context.Attributes)
                {
                    cancellationToken.ThrowIfCancellationRequested();
                    if (attribute.TryGetTestAttributeData(out var data))
                    {
                        builder.Add(data);
                    }
                }
                if (builder.Count == 0)
                {
                    return (Value: default(T)!, IsMatch: false);
                }
                return (Value: transform(context, builder.ToImmutable(), cancellationToken), IsMatch: true);
            });
        var matches = global::Microsoft.CodeAnalysis.IncrementalValueProviderExtensions.Where(results, result => result.IsMatch);
        return global::Microsoft.CodeAnalysis.IncrementalValueProviderExtensions.Select(matches, (result, _) => result.Value);
    }
}
file sealed class TestAttributeDataConstructor : global::ZCrew.Extensions.CodeAnalysis.CSharp.AttributeConstructor<TestAttributeData>
{
    private static readonly TestAttributeDataConstructor constructor0 = new([TestAttributeDataParameter.Matches, TestAttributeDataParameter.EqualsString, TestAttributeDataParameter.ToStringString]);
    public static readonly TestAttributeDataConstructor[] TestAttributeDataConstructors = [constructor0];
    protected override string AttributeMetadataName => "AttributeTests.TestAttribute";
    public TestAttributeDataConstructor(global::ZCrew.Extensions.CodeAnalysis.CSharp.AttributeParameter<TestAttributeData>[] parameters) : base([], parameters, TestAttributeDataNamedParameter.TestAttributeDataNamedParameters) { }
}
file sealed class TestAttributeDataParameter : global::ZCrew.Extensions.CodeAnalysis.CSharp.AttributeParameter<TestAttributeData>
{
    public static readonly TestAttributeDataParameter Matches = new("string", (model, constant) => global::ZCrew.Extensions.CodeAnalysis.CSharp.TypedConstantExtensions.GetValue(constant, out model.Matches));
    public static readonly TestAttributeDataParameter EqualsString = new("string", (model, constant) => global::ZCrew.Extensions.CodeAnalysis.CSharp.TypedConstantExtensions.GetValue(constant, out model.EqualsString));
    public static readonly TestAttributeDataParameter ToStringString = new("string", (model, constant) => global::ZCrew.Extensions.CodeAnalysis.CSharp.TypedConstantExtensions.GetValue(constant, out model.ToStringString));
    public TestAttributeDataParameter(string type, global::System.Action<TestAttributeData, global::Microsoft.CodeAnalysis.TypedConstant> valueAction) : base(type, valueAction) { }
}
file sealed class TestAttributeDataNamedParameter : global::ZCrew.Extensions.CodeAnalysis.CSharp.AttributeNamedParameter<TestAttributeData>
{
    private static readonly TestAttributeDataNamedParameter ToStringObject = new("ToString", (model, _, constant) => global::ZCrew.Extensions.CodeAnalysis.CSharp.TypedConstantExtensions.GetValue(constant, out model.ToStringObject));
    private static readonly TestAttributeDataNamedParameter GetHashCodeString = new("GetHashCode", (model, _, constant) => global::ZCrew.Extensions.CodeAnalysis.CSharp.TypedConstantExtensions.GetValue(constant, out model.GetHashCodeString));
    internal static readonly global::ZCrew.Extensions.CodeAnalysis.CSharp.AttributeNamedParameter<TestAttributeData>[] TestAttributeDataNamedParameters = [ToStringObject, GetHashCodeString];
    public TestAttributeDataNamedParameter(string name, global::System.Action<TestAttributeData, string, global::Microsoft.CodeAnalysis.TypedConstant> valueAction) : base(name, valueAction) { }
}
