using System.Collections.Immutable;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using ZCrew.Extensions.CodeAnalysis.CSharp.Collections;
using ZCrew.Extensions.CodeAnalysis.CSharp.Text;

namespace EnumToStringFast;

[Generator]
public class EnumToStringFastSourceGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static context =>
        {
            context.AddEmbeddedAttributeDefinition();
            context.AddSource("ToStringFastAttribute.g.cs", ToStringFastAttributeSourceText.SourceText);
        });

        var nonGenericEnums = context.SyntaxProvider.ForAttributeWithMetadataName(
            "EnumToStringFast.ToStringFastAttribute",
            static (node, _) => node is EnumDeclarationSyntax,
            static (context, _) => CreateEnumInfoFromEnum(context)
        );

        var genericClasses = context.SyntaxProvider.ForAttributeWithMetadataName(
            "EnumToStringFast.ToStringFastAttribute`1",
            static (node, _) => node is ClassDeclarationSyntax,
            static (context, _) => CreateEnumInfoFromClass(context)
        );

        context.RegisterSourceOutput(nonGenericEnums, static (context, enumInfo) =>
        {
            var source = GenerateExtensionClass(enumInfo);
            var name = enumInfo.ExtensionClassNamespace is not null
                ? $"{enumInfo.ExtensionClassNamespace}.{enumInfo.ExtensionClassName}.g.cs"
                : $"{enumInfo.ExtensionClassName}.g.cs";
            context.AddSource(name, source);
        });

        context.RegisterSourceOutput(genericClasses, static (context, enumInfo) =>
        {
            var source = GenerateExtensionClass(enumInfo);
            var name = enumInfo.ExtensionClassNamespace is not null
                ? $"{enumInfo.ExtensionClassNamespace}.{enumInfo.ExtensionClassName}.g.cs"
                : $"{enumInfo.ExtensionClassName}.g.cs";
            context.AddSource(name, source);
        });
    }

    private static EnumToStringFastInfo CreateEnumInfoFromEnum(
        GeneratorAttributeSyntaxContext context
    )
    {
        var enumSymbol = (INamedTypeSymbol)context.TargetSymbol;
        var enumName = enumSymbol.Name;
        var enumNamespace = enumSymbol.ContainingNamespace.IsGlobalNamespace
            ? null
            : enumSymbol.ContainingNamespace.ToDisplayString();

        var members = enumSymbol
            .GetMembers()
            .OfType<IFieldSymbol>()
            .Where(f => f.HasConstantValue)
            .Select(f => f.Name)
            .ToImmutableArray()
            .ToEquatableArray();

        var builder = new ToStringFastAttributeDataBuilder();
        foreach (var attributeData in context.Attributes)
        {
            ToStringFastAttributeConstructor.WithAttributeData(builder, attributeData);
        }

        var data = builder.Build();

        var extensionClassNamespace = data.ExtensionClassNamespace ?? enumNamespace;
        var extensionClassName = data.ExtensionClassName ?? $"{enumName}Extensions";

        return new EnumToStringFastInfo(
            enumName,
            enumNamespace,
            extensionClassNamespace,
            extensionClassName,
            members
        );
    }

    private static EnumToStringFastInfo CreateEnumInfoFromClass(
        GeneratorAttributeSyntaxContext context
    )
    {
        // Extension class info comes from the target symbol (the decorated class)
        var classSymbol = (INamedTypeSymbol)context.TargetSymbol;
        var extensionClassName = classSymbol.Name;
        var extensionClassNamespace = classSymbol.ContainingNamespace.IsGlobalNamespace
            ? null
            : classSymbol.ContainingNamespace.ToDisplayString();

        // Enum info and members come from the builder — WithEnum is called by the
        // generated ToStringFastAttributeConstructor for the TEnum type parameter
        var builder = new ToStringFastAttributeDataBuilder();
        foreach (var attributeData in context.Attributes)
        {
            ToStringFastAttributeConstructor.WithAttributeData(builder, attributeData);
        }

        var data = builder.Build();

        return new EnumToStringFastInfo(
            data.EnumName!,
            data.EnumNamespace,
            extensionClassNamespace,
            extensionClassName,
            data.Members
        );
    }

    private static string GenerateExtensionClass(EnumToStringFastInfo info)
    {
        var enumFullName = info.EnumNamespace is not null
            ? $"global::{info.EnumNamespace}.{info.EnumName}"
            : $"global::{info.EnumName}";

        var builder = new FormattedStringBuilder();
        builder
            .AppendLine("// <auto-generated/>")
            .AppendNullableEnable()
            .AppendCommonPragmaDisable()
            .AppendLine();

        builder.AppendFileScopedNamespaceDeclaration(info.ExtensionClassNamespace);

        if (info.ExtensionClassNamespace is not null)
        {
            builder.AppendLine();
        }

        builder
            .Append($"internal static partial class {info.ExtensionClassName}")
            .AppendLine()
            .Append('{')
            .Indent()
            .AppendLine()
            .Append(
                $"public static string ToStringFast(this {enumFullName} value) => value switch"
            )
            .AppendLine()
            .Append('{')
            .Indent();

        foreach (var member in info.Members)
        {
            builder
                .AppendLine()
                .Append(
                    $"{enumFullName}.{member} => nameof({enumFullName}.{member}),"
                );
        }

        builder
            .AppendLine()
            .Append("_ => value.ToString(),")
            .Unindent()
            .AppendLine()
            .Append("};")
            .Unindent()
            .AppendLine()
            .Append('}');

        return builder.ToString();
    }
}
